version: "3.8"
services:
  backend:
    build:
      context: ./backend  # Path to the directory containing the backend Dockerfile
    ports:
      - "8000:8000"  # Map port 8000 of the container to port 8000 of the host machine
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/school-project  # Path to the directory containing the frontend Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 of the host machine

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"  # Map port 3306 of the container to port 3306 of the host machine
    volumes:
      - ./mysql-data:/var/lib/mysql  # Mount a volume to persist MySQL data
